export const DEFAULT_PAGE_SIZE = {
  FEEDBACK: 20,
  WALLET: 10,
  QUESTIONS: 10,
  REDEEM: 20,
  USAGE_LOGS: 20,
  SYSTEM_LOGS: 50,
  MODELS: 10,
  CALL_TRACES: 50,
}

export const SYSTEM_DEFAULTS = {
  LLM_CACHE_MIN_CONFIDENCE: 0.95,
  LLM_CACHE_MIN_CONFIRMATIONS: 2,
  LOG_REFRESH_INTERVAL_MS: 5000,
}
